name: Deploy the website

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency: deploy-web-prod
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
          cache: "yarn"

      - name: Install app deps
        working-directory: ./app
        run: yarn install
      - name: Build app
        working-directory: ./app
        run: yarn build

      - name: Install pulumi deps
        working-directory: ./pulumi
        run: yarn install
#      - name: Pulumi up
#        uses: pulumi/actions@v3
#        with:
#          command: up
#          stack-name: prod
#          work-dir: pulumi
#        env:
#          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
